In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [12]:
file_path = "C:\\Users\\swapn\\OneDrive\\Desktop\\Dev\\Zidio_Development_Internship\\dataset\\Online Retail.xlsx"

df = pd.read_excel(file_path)

print("Original shape:", df.shape)
df.head()

Original shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [13]:
print(df.info())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB
None

Missing values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Duplicate rows:
5268

In [14]:
df.columns = df.columns.str.strip()

df.rename(columns={
    "InvoiceNo": "invoice_no",
    "StockCode": "stock_code",
    "Description": "description",
    "Quantity": "quantity",
    "InvoiceDate": "invoice_date",
    "UnitPrice": "unit_price",
    "CustomerID": "customer_id",
    "Country": "country"
}, inplace=True)

df.head()

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [15]:
df["invoice_no"] = df["invoice_no"].astype(str).str.strip()
df["stock_code"] = df["stock_code"].astype(str).str.strip()
df["description"] = df["description"].astype(str).str.strip()
df["country"] = df["country"].astype(str).str.strip()

df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["unit_price"] = pd.to_numeric(df["unit_price"], errors="coerce")
df["customer_id"] = pd.to_numeric(df["customer_id"], errors="coerce")

df["invoice_date"] = pd.to_datetime(
    df["invoice_date"],
    errors="coerce"
)

print(df.dtypes)

invoice_no                 str
stock_code                 str
description                str
quantity                 int64
invoice_date    datetime64[us]
unit_price             float64
customer_id            float64
country                    str
dtype: object

In [16]:
print("Missing invoice_date:", df["invoice_date"].isnull().sum())
print("Date range:", df["invoice_date"].min(), "to", df["invoice_date"].max())

df[["invoice_no", "invoice_date"]].head()

Missing invoice_date: 0
Date range: 2010-12-01 08:26:00 to 2011-12-09 12:50:00

  invoice_no        invoice_date
0     536365 2010-12-01 08:26:00
1     536365 2010-12-01 08:26:00
2     536365 2010-12-01 08:26:00
3     536365 2010-12-01 08:26:00
4     536365 2010-12-01 08:26:00

In [17]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates().copy()

print("Duplicates after:", df.duplicated().sum())
print("Shape after duplicate removal:", df.shape)

Duplicates before: 5268
Duplicates after: 0
Shape after duplicate removal: (536641, 8)

In [18]:
df["description"] = df["description"].replace(["nan", "NaN", "", "None"], np.nan)
df["description"] = df["description"].fillna("Unknown Product")

df["customer_id_missing"] = df["customer_id"].isnull().astype(int)

print(df.isnull().sum())

invoice_no                  0
stock_code                  0
description                 0
quantity                    0
invoice_date                0
unit_price                  0
customer_id            135037
country                     0
customer_id_missing         0
dtype: int64

In [19]:
df["is_cancelled"] = df["invoice_no"].str.startswith("C").astype(int)

print(df["is_cancelled"].value_counts())

cancelled_df = df[df["is_cancelled"] == 1].copy()

cancelled_df.head()

is_cancelled
0    527390
1      9251
Name: count, dtype: int64

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,customer_id_missing,is_cancelled
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom,0,1
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom,0,1
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,0,1
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,0,1
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,0,1

In [21]:
clean_df = df[df["is_cancelled"] == 0].copy()

clean_df = clean_df[
    (clean_df["quantity"] > 0) &
    (clean_df["unit_price"] > 0) &
    (clean_df["invoice_date"].notna())
].copy()

print("Clean sales shape:", clean_df.shape)
clean_df.head()

Clean sales shape: (524878, 10)

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,customer_id_missing,is_cancelled
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,0,0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,0,0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0

In [22]:
clean_df["description"] = clean_df["description"].str.strip().str.lower()
clean_df["country"] = clean_df["country"].str.strip().str.title()
clean_df["stock_code"] = clean_df["stock_code"].str.strip()

clean_df.head()

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,customer_id_missing,is_cancelled
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,0,0
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,0,0
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0

In [23]:
clean_df["total_amount"] = clean_df["quantity"] * clean_df["unit_price"]

clean_df[["quantity", "unit_price", "total_amount"]].describe()

            quantity     unit_price   total_amount
count  524878.000000  524878.000000  524878.000000
mean       10.616600       3.922573      20.275399
std       156.280031      36.093028     271.693566
min         1.000000       0.001000       0.001000
25%         1.000000       1.250000       3.900000
50%         4.000000       2.080000       9.920000
75%        11.000000       4.130000      17.700000
max     80995.000000   13541.330000  168469.600000

In [24]:
clean_df["date"] = clean_df["invoice_date"].dt.date
clean_df["year"] = clean_df["invoice_date"].dt.year
clean_df["month"] = clean_df["invoice_date"].dt.month
clean_df["day"] = clean_df["invoice_date"].dt.day
clean_df["day_of_week"] = clean_df["invoice_date"].dt.day_name()
clean_df["hour"] = clean_df["invoice_date"].dt.hour
clean_df["year_month"] = clean_df["invoice_date"].dt.to_period("M").astype(str)

clean_df.head()

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,customer_id_missing,is_cancelled,total_amount,date,year,month,day,day_of_week,hour,year_month
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,0,0,15.30,2010-12-01,2010,12,1,Wednesday,8,2010-12
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0,20.34,2010-12-01,2010,12,1,Wednesday,8,2010-12
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,0,0,22.00,2010-12-01,2010,12,1,Wednesday,8,2010-12
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0,20.34,2010-12-01,2010,12,1,Wednesday,8,2010-12
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,0,0,20.34,2010-12-01,2010,12,1,Wednesday,8,2010-12

In [25]:
customer_df = clean_df.dropna(subset=["customer_id"]).copy()

customer_df["customer_id"] = customer_df["customer_id"].astype(int).astype(str)

print("Customer sales shape:", customer_df.shape)
customer_df.head()

Customer sales shape: (392692, 18)

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,customer_id_missing,is_cancelled,total_amount,date,year,month,day,day_of_week,hour,year_month
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,0,0,15.30,2010-12-01,2010,12,1,Wednesday,8,2010-12
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,0,0,20.34,2010-12-01,2010,12,1,Wednesday,8,2010-12
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,0,0,22.00,2010-12-01,2010,12,1,Wednesday,8,2010-12
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,0,0,20.34,2010-12-01,2010,12,1,Wednesday,8,2010-12
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,0,0,20.34,2010-12-01,2010,12,1,Wednesday,8,2010-12

In [26]:
print("Clean sales shape:", clean_df.shape)
print("Customer sales shape:", customer_df.shape)
print("Cancelled orders shape:", cancelled_df.shape)

print("\nMissing values in clean_df:")
print(clean_df.isnull().sum())

print("\nDuplicate rows in clean_df:")
print(clean_df.duplicated().sum())

print("\nDate range:")
print(clean_df["invoice_date"].min(), "to", clean_df["invoice_date"].max())

Clean sales shape: (524878, 18)
Customer sales shape: (392692, 18)
Cancelled orders shape: (9251, 10)

Missing values in clean_df:
invoice_no                  0
stock_code                  0
description                 0
quantity                    0
invoice_date                0
unit_price                  0
customer_id            132186
country                     0
customer_id_missing         0
is_cancelled                0
total_amount                0
date                        0
year                        0
month                       0
day                         0
day_of_week                 0
hour                        0
year_month                  0
dtype: int64

Duplicate rows in clean_df:
0

Date range:
2010-12-01 08:26:00 to 2011-12-09 12:50:00

In [ ]:
clean_df.to_csv("../data/processed/cleaned_online_retail_all_sales.csv", index=False)
customer_df.to_csv("../data/processed/cleaned_online_retail_customer_sales.csv", index=False)
cancelled_df.to_csv("../data/processed/cancelled_orders.csv", index=False)

print("Cleaned files saved successfully.")

Cleaned files saved successfully.